In [1]:
%load_ext autoreload
%autoreload 2
import numpy as np
import yroots as yr
from yroots.LinearProjection import *

# Example 
$p_1 = T_3(y)T_2(z) + T_2(x)T_2(y) + T_2(x)T_1(z)$

$p_2 = 1 + x + y - z$

$p_2 = 1 + x - z$

In [2]:
oldcoeff = np.zeros((3,4,3))                                                                                                         
oldcoeff[0,3,2]=1                                                                                                                    
oldcoeff[2,2,0]=1                                                                                                                    
oldcoeff[2,0,1]=1    
oldcoeff

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 1., 0.],
        [0., 0., 0.],
        [1., 0., 0.],
        [0., 0., 0.]]])

In [3]:
oldcoeff2 = np.zeros((3,4,3))                                                                                                         
oldcoeff2[0,3,2]=1                                                                                                                    
oldcoeff2[2,2,0]=1                                                                                                                    
oldcoeff2[2,0,1]=1   
oldcoeff2[1,0,0]=1
oldcoeff2[0,1,0]=2
oldcoeff2[0,0,1]=3
oldcoeff2

array([[[0., 3., 0.],
        [2., 0., 0.],
        [0., 0., 0.],
        [0., 0., 1.]],

       [[1., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 1., 0.],
        [0., 0., 0.],
        [1., 0., 0.],
        [0., 0., 0.]]])

In [4]:
Td = get_Td_expressions([1,0,1],3)

In [5]:
print(*Td.values(),sep='\n')

[[1.]]
[[1. 1.]]
[[2. 4. 1.]]
[[ 7. 12.  6.  1.]]


In [6]:
oldcoeff.shape

(3, 4, 3)

In [7]:
mon_combos([0]*2,5)

[[0, 0],
 [0, 1],
 [0, 2],
 [0, 3],
 [0, 4],
 [0, 5],
 [1, 0],
 [1, 1],
 [1, 2],
 [1, 3],
 [1, 4],
 [2, 0],
 [2, 1],
 [2, 2],
 [2, 3],
 [3, 0],
 [3, 1],
 [3, 2],
 [4, 0],
 [4, 1],
 [5, 0]]

In [8]:
transform_coeff_matrix(oldcoeff,Td,[1,0,1],2)

TypeError: only integer scalar arrays can be converted to a scalar index

In [ ]:
lin_combo = oldcoeff2[tuple(get_var_list(3))]
lin_combo

In [ ]:
old = [1,[2],3,4]
new = old.copy()
new,old

In [ ]:
new[1][0] = 0 
new,old

In [ ]:
oldcoeff3 = np.zeros((3,4,3))                                                                                                         
oldcoeff3[0,3,0]=1                                                                                                                    
oldcoeff3[2,2,0]=1                                                                                                                    
oldcoeff3[2,0,0]=1   
oldcoeff3[1,0,0]=1
oldcoeff3[0,1,0]=2
oldcoeff3[0,0,0]=3
oldcoeff3

In [ ]:
np.nonzero([1,0])