In [2]:
%load_ext autoreload
%autoreload 2
import numpy as np
import yroots as yr
from yroots.LinearProjection import *

In [26]:
oldcoeff = np.zeros((3,4,3))                                                                                                         
oldcoeff[0,3,2]=1                                                                                                                    
oldcoeff[2,2,0]=1                                                                                                                    
oldcoeff[2,0,1]=1    
oldcoeff

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 1., 0.],
        [0., 0., 0.],
        [1., 0., 0.],
        [0., 0., 0.]]])

In [53]:
print(*get_Td_expressions([1,1,1],3)[0].values(),sep='\n')

[[1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[3. 4. 1. 0.]
 [4. 4. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[13. 18.  6.  1.]
 [18. 24.  6.  0.]
 [ 6.  6.  0.  0.]
 [ 1.  0.  0.  0.]]


In [54]:
oldcoeff.shape

(3, 4, 3)

In [79]:
transform_coeff_matrix(oldcoeff,[1,1,1],2)

(0, 3)
(0, 3)
(0, 3)
(0, 3)
(0, 4)
(0, 2)
(0, 4)
(0, 2)
(0, 5)
(0, 1)
(0, 5)
(0, 1)
(1, 3)
(1, 3)
(1, 3)
(1, 3)
(1, 4)
(1, 2)
(1, 4)
(1, 2)
(2, 3)
(2, 3)
(2, 3)
(2, 3)
(2, 0)
(2, 0)
(2, 0)
(2, 0)
(2, 1)
(2, 1)
(2, 1)
(2, 1)
(3, 0)
(3, 0)
(1, 0)
(1, 0)


array([[0. , 0.5, 2. , 3. , 2. , 0.5],
       [0.5, 0. , 2. , 4. , 2. , 0. ],
       [1. , 1. , 1. , 1. , 0. , 0. ],
       [0.5, 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. ]])