### Groebner Basis Calculation Tutorial

In [1]:
#Conda imports
import numpy as np
import pandas as pd
from scipy.linalg import lu

#Local imports
from groebner import MultiCheb, MultiPower, maxheap
from groebner.groebner_class import Groebner

# Auto-reload packages
%load_ext autoreload
%autoreload 2


ModuleNotFoundError: No module named 'groebner'

# Example 1:
### 3 dimensional system (Currently not working)

In [ ]:
# Example of a 3x3 system 

# Currently not converging


A = MultiPower(np.array([
    [[1,1,3],[0,0,2],[6,4,3]],
    [[1,2,3],[1,3,2],[5,1,4]],
    [[2,4,3],[4,1,2],[4,2,3]]
                        ]))
B = MultiPower(np.array([
    [[1,3,3],[0,3,2],[6,4,3]],
    [[3,2,3],[1,13,1],[5,4,5]],
    [[2,1,3],[4,1,2],[2,1,2]]
                        ]))

C = MultiPower(np.array([
    [[2,3,3],[0,3,-2],[-6,4,3]],
    [[-3,2,3],[1,1,1],[5,4,5]],
    [[2,1,-3],[-4,1,2],[-2,1,2]]
                        ]))

grob = Groebner([A,B,C])
grob.solve()

# Example 2:
### 2 Dimensional system

In [5]:
# Example of a 4x4

A = MultiPower(np.array([[1,0,-2,1],[2,0,5,1],[1,0,4,1],[2,0,3,1]]))
B = MultiPower(np.array([[1,0,8,7],[1,0,1,2],[0,4,1,2],[0,1,5,4]]))

grob = Groebner([A,B])
grob.solve()

Starting Loop #1
(2, 14)
ADDING PHI's
(4, 14)
ADDING r's
(4, 14)
Starting Loop #2
(5, 14)
ADDING PHI's
(23, 23)
ADDING r's
(25, 23)
Starting Loop #3
(22, 22)
ADDING PHI's
(464, 50)
ADDING r's
(484, 50)
WE WIN
[[ -6.66133815e-16   8.01257620e-16  -3.99680289e-15  -8.18789481e-15
    2.33676886e-15   1.99480347e-16]
 [ -7.77156117e-16   1.86960111e-15  -1.11022302e-15   3.87190280e-15
   -9.73842453e-16  -1.55191376e-32]
 [ -1.11022302e-16  -1.11022302e-15  -2.44249065e-15   4.48252546e-15
    0.00000000e+00   0.00000000e+00]
 [ -2.22044605e-16   1.59594560e-15  -4.05231404e-15   0.00000000e+00
    0.00000000e+00   0.00000000e+00]
 [ -2.46519033e-32   1.23259516e-32   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00]]
[[ -3.66144281e-17  -2.07771866e-16  -8.06165938e-17  -3.91258088e-16
    5.85454549e-17  -3.04361067e-33]
 [  4.18400467e-17  -4.22344634e-16  -6.81322122e-16  -7.58447288e-16
   -5.38301595e-17   0.00000000e+00]
 [  3.90394586e-16  -3.03071977e-16  -5.1

# Example 3:
### A step by step example

In [6]:
# Let's take it one step at a time.
A = MultiPower(np.array([[1,1],[2,3]]))
B = MultiPower(np.array([[1,1],[3,4]]))
C = MultiPower(np.array([[5,2],[2,4]]))
D = MultiPower(np.array([[1,1,1],[2,2,2],[3,3,3]]))

grob = Groebner([A,B,C,D])
grob.initialize_np_matrix()

print(grob.np_matrix.shape)
print(grob.np_matrix)



(4, 9)
[[ 2.  2.  1.  1.  3.  3.  2.  3.  1.]
 [ 4.  2.  2.  5.  0.  0.  0.  0.  0.]
 [ 4.  3.  1.  1.  0.  0.  0.  0.  0.]
 [ 3.  2.  1.  1.  0.  0.  0.  0.  0.]]


In [7]:
# Add some phi's
grob.add_phi_to_matrix()
print(grob.np_matrix.shape)
print(grob.np_matrix)

(16, 9)
[[ 2.  2.  1.  1.  3.  3.  2.  3.  1.]
 [ 5.  0.  0.  0.  4.  2.  2.  0.  0.]
 [ 2.  2.  1.  1.  3.  3.  2.  3.  1.]
 [ 1.  0.  0.  0.  4.  3.  1.  0.  0.]
 [ 4.  2.  2.  5.  0.  0.  0.  0.  0.]
 [ 4.  3.  1.  1.  0.  0.  0.  0.  0.]
 [ 2.  2.  1.  1.  3.  3.  2.  3.  1.]
 [ 1.  0.  0.  0.  3.  2.  1.  0.  0.]
 [ 4.  2.  2.  5.  0.  0.  0.  0.  0.]
 [ 3.  2.  1.  1.  0.  0.  0.  0.  0.]
 [ 4.  3.  1.  1.  0.  0.  0.  0.  0.]
 [ 3.  2.  1.  1.  0.  0.  0.  0.  0.]
 [ 2.  2.  1.  1.  3.  3.  2.  3.  1.]
 [ 4.  2.  2.  5.  0.  0.  0.  0.  0.]
 [ 4.  3.  1.  1.  0.  0.  0.  0.  0.]
 [ 3.  2.  1.  1.  0.  0.  0.  0.  0.]]


In [8]:
# Add some r's
grob.add_r_to_matrix()
print(grob.np_matrix.shape)
print(grob.np_matrix)



(18, 9)
[[ 0.  0.  3.  0.  2.  1.  0.  1.  0.]
 [ 0.  3.  0.  2.  1.  0.  1.  0.  0.]
 [ 3.  3.  2.  3.  2.  1.  2.  1.  1.]
 [ 4.  2.  2.  0.  5.  0.  0.  0.  0.]
 [ 3.  3.  2.  3.  2.  1.  2.  1.  1.]
 [ 4.  3.  1.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  4.  0.  2.  2.  5.]
 [ 0.  0.  0.  0.  4.  0.  3.  1.  1.]
 [ 3.  3.  2.  3.  2.  1.  2.  1.  1.]
 [ 3.  2.  1.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  4.  0.  2.  2.  5.]
 [ 0.  0.  0.  0.  3.  0.  2.  1.  1.]
 [ 0.  0.  0.  0.  4.  0.  3.  1.  1.]
 [ 0.  0.  0.  0.  3.  0.  2.  1.  1.]
 [ 3.  3.  2.  3.  2.  1.  2.  1.  1.]
 [ 0.  0.  0.  0.  4.  0.  2.  2.  5.]
 [ 0.  0.  0.  0.  4.  0.  3.  1.  1.]
 [ 0.  0.  0.  0.  3.  0.  2.  1.  1.]]


In [9]:
# Reduce
polys_added = grob.reduce_matrix(qr_reduction=True)

In [10]:
# Rinse Repeat
grob.initialize_np_matrix()
print(grob.np_matrix.shape)
print(grob.np_matrix)



(9, 9)
[[ 3.          2.          1.          2.          1.          1.          3.
   3.          2.        ]
 [ 0.          4.          0.          2.          2.          5.          0.
   0.          0.        ]
 [ 0.          4.          0.          3.          1.          1.          0.
   0.          0.        ]
 [ 0.          3.          0.          2.          1.          1.          0.
   0.          0.        ]
 [ 0.          0.          0.          0.          0.         -1.13389342
   0.          0.          0.        ]
 [ 0.          0.          0.          0.         -0.6197954  -2.03647061
   0.          0.          0.        ]
 [ 0.          0.          0.          1.30703226 -1.09981983 -4.73400709
   0.          0.          0.        ]
 [ 0.          0.         -0.34908096 -1.76832425 -1.3143427  -1.92787893
   0.          0.          0.        ]
 [ 2.76868107 -0.65036132  0.78740175  1.97663388  0.78740175  1.1845867
   0.          0.          0.        ]]


# Example 3.1:
### Example 3, solved in one step

In [11]:
# All at once yields
A = MultiPower(np.array([[1,1],[2,3]]))
B = MultiPower(np.array([[1,1],[3,4]]))
C = MultiPower(np.array([[5,2],[2,4]]))
D = MultiPower(np.array([[1,1,1],[2,2,2],[3,3,3]]))

grob = Groebner([A,B,C,D])
grob.solve()

Starting Loop #1
(4, 9)
ADDING PHI's
(16, 9)
ADDING r's
(18, 9)
Starting Loop #2
(9, 9)
ADDING PHI's
(69, 13)
ADDING r's
(73, 13)
WE WIN
[[ 1.1845867   0.78740175  0.78740175]
 [ 1.97663388 -0.65036132  0.        ]
 [ 2.76868107  0.          0.        ]]
[[-1.92787893 -1.3143427  -0.34908096]
 [-1.76832425  0.          0.        ]
 [ 0.          0.          0.        ]]
[[-4.73400709 -1.09981983  0.        ]
 [ 1.30703226  0.          0.        ]
 [ 0.          0.          0.        ]]
[[-2.03647061 -0.6197954   0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
[[-1.13389342  0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
[[1 1]
 [2 3]]
[[1 1]
 [3 4]]
[[5 2]
 [2 4]]
[[1 1 1]
 [2 2 2]
 [3 3 3]]


# Example 4:
### A known Gröner Basis to show that it does what we claim

In [15]:
# 1+x, 1+y

A = MultiPower(np.array([[1,1],[0,0]]))
B = MultiPower(np.array([[1,0],[1,0]]))

grob = Groebner([A,B])


#grob.solve()

In [16]:
grob.initialize_np_matrix()

print(grob.np_matrix.shape)
print(grob.np_matrix)



(2, 3)
[[ 0.  1.  1.]
 [ 1.  1.  0.]]


In [17]:
# Add some phi's
grob.add_phi_to_matrix()
print(grob.np_matrix.shape)
print(grob.np_matrix)

(4, 4)
[[ 1.  0.  0.  1.]
 [ 0.  0.  1.  1.]
 [ 0.  1.  1.  0.]
 [ 1.  1.  0.  0.]]


In [18]:
# Add some r's
grob.add_r_to_matrix()
print(grob.np_matrix.shape)
print(grob.np_matrix)




(4, 4)
[[ 1.  0.  1.  0.]
 [ 1.  1.  0.  0.]
 [ 0.  1.  0.  1.]
 [ 0.  0.  1.  1.]]


In [19]:
# Reduce
polys_added = grob.reduce_matrix(qr_reduction=True)

# Rinse Repeat
grob.initialize_np_matrix()
print(grob.np_matrix.shape)
print(grob.np_matrix)



(3, 3)
[[  1.00000000e+00   0.00000000e+00   1.00000000e+00]
 [  1.00000000e+00   1.00000000e+00   0.00000000e+00]
 [ -7.64210971e-17   0.00000000e+00   0.00000000e+00]]


# Example 5:
## A trivial Gröner Basis



In [21]:

A = MultiPower(np.array([[1,1],[0,0]]))
B = MultiPower(np.array([[1,0],[1,0]]))
C = MultiPower(np.array([[1,1,0],[0,0,1],[0,0,0]]))
grob = Groebner([A,B,C])

grob.solve()


Starting Loop #1
(3, 4)
ADDING PHI's
(9, 6)
ADDING r's
(10, 6)
Starting Loop #2
(4, 4)
ADDING PHI's
(10, 4)
ADDING r's
(10, 4)
WE WIN
[[-0.52223297  0.          0.        ]
 [ 0.          0.          0.        ]]
[[1 1]
 [0 0]]
[[1 0]
 [1 0]]
[[1 1 0]
 [0 0 1]
 [0 0 0]]


In [24]:
# Using LU
A = MultiPower(np.array([[1,1],[0,0]]))
B = MultiPower(np.array([[1,0],[1,0]]))
C = MultiPower(np.array([[1,1,0],[0,0,1]]))
grob = Groebner([A,B,C])

grob.solve(qr_reduction=False)



Starting Loop #1
(3, 4)
ADDING PHI's
(9, 6)
ADDING r's
(10, 6)
Starting Loop #2
(4, 4)
ADDING PHI's
(10, 4)
ADDING r's
(10, 4)
WE WIN
[[ 0.5  0.   0. ]
 [ 0.   0.   0. ]]
[[1 1]
 [0 0]]
[[1 0]
 [1 0]]
[[1 1 0]
 [0 0 1]]
